version: '2'

services:
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../public:/usr/share/nginx/html
            - ../var/log:/var/log
            - ./nginx/root_home:/root
        ports:
            - "80:80"
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - cfml-in-docker.frontend

    lucee:
        build:
            context: ./lucee
            args:
                - LUCEE_PASSWORD=${LUCEE_PASSWORD}
        environment:
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ../var/log/tomcat:/usr/local/tomcat/log
            - ../var/log/lucee:/opt/lucee/web/logs
            - ./lucee/root_home/.bash_history:/root/.bash_history
        ports:
            - "8888:8888"
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - cfml-in-docker.lucee

    mariadb:
        build:
            context: ./mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysqlData:/var/lib/mariadb
            - ./mariadb/root_home:/root
            - ../var/log:/var/log
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - database.backend

volumes:
    mysqlData:

networks:
    backend:
        driver: "bridge"
