version: '2'

services:
    php-cli:
        build:
            context: ./php-cli
        volumes:
            - ./php-cli/root_home/.bash_history:/root/.bash_history
            - ../test/php:/usr/share/cfml-in-docker/test/php
            - ../composer.json:/usr/share/cfml-in-docker/composer.json
            - ../composer.lock:/usr/share/cfml-in-docker/composer.lock
            - ../phpunit.xml.dist:/usr/share/cfml-in-docker/phpunit.xml.dist
        stdin_open: true
        tty: true
        networks:
            - backend

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../public:/usr/share/nginx/html
            - ../var/log:/var/log
            - ./nginx/root_home:/root
        ports:
            - "80:80"
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - cfml-in-docker.frontend

    lucee:
        build:
            context: ./lucee
            args:
                - LUCEE_PASSWORD=${LUCEE_PASSWORD}
        environment:
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ../root/src:/var/www/src
            - ../test:/var/www/test
            - ../public:/var/www/public
            - ../var/log/tomcat:/usr/local/tomcat/log
            - ../var/log/lucee:/opt/lucee/web/logs
            - ./lucee/root_home:/root
        ports:
            - "8888:8888"
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - cfml-in-docker.lucee

    mariadb:
        build:
            context: ./mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysqlData:/var/lib/mysql
            - ./mariadb/root_home:/root
            - ../var/log:/var/log
        stdin_open: true
        tty: true
        networks:
            backend:
                aliases:
                    - database.backend

volumes:
    mysqlData:

networks:
    backend:
        driver: "bridge"
